import {Inter} from "next/font/google";
import "./globals.css";
import {NextUIProvider} from "@nextui-org/react";
import MainNavbar from "@/components/MainNavbar";
import React from "react";

const inter = Inter({subsets: ["latin"]});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}) {
  return (
    <html lang="en">
    <body
      className={`${inter.className}, text-white bg-orange-50 min-h-screen`}
    >
    <NextUIProvider>
      <main className="dark text-foreground bg-background">
        <div className="sticky top-0 w-full z-50">
          <MainNavbar/>
        </div>
        <div className="container py-5 mx-auto">
          {children}
        </div>
      </main>
    </NextUIProvider>
    </body>
    </html>
  );
}